import { Document, Page, View, Text, StyleSheet } from "@react-pdf/renderer";

export type ReportData = {
  companyName: string;
  filename: string;
  date: string;
  totalSpend: number;
  totalExposure: number;
  effectiveRate: number;
  itemsAtRisk: number;
  items: Array<{
    item_name: string;
    supplier_country: string;
    annual_spend: number;
    tariff_rate: number;
    tariff_cost: number;
    risk_level: string;
  }>;
};

const s = StyleSheet.create({
  page: { padding: 40, fontSize: 9, fontFamily: "Helvetica", color: "#1a1a1a" },
  header: { flexDirection: "row", justifyContent: "space-between", marginBottom: 20 },
  brand: { fontSize: 16, fontFamily: "Helvetica-Bold" },
  date: { fontSize: 9, color: "#666" },
  sub: { fontSize: 11, marginBottom: 4, color: "#333" },
  filename: { fontSize: 9, color: "#666", marginBottom: 16 },
  statsRow: { flexDirection: "row", marginBottom: 20, gap: 12 },
  statBox: { flex: 1, padding: 10, backgroundColor: "#f5f5f5", borderRadius: 4 },
  statLabel: { fontSize: 7, color: "#888", marginBottom: 3, textTransform: "uppercase" },
  statValue: { fontSize: 13, fontFamily: "Helvetica-Bold" },
  tableHeader: {
    flexDirection: "row", backgroundColor: "#f0f0f0", padding: 6,
    borderBottomWidth: 1, borderBottomColor: "#ddd",
  },
  tableRow: { flexDirection: "row", padding: 6, borderBottomWidth: 0.5, borderBottomColor: "#eee" },
  colName: { width: "25%" },
  colCountry: { width: "15%" },
  colSpend: { width: "15%", textAlign: "right" },
  colRate: { width: "10%", textAlign: "right" },
  colCost: { width: "15%", textAlign: "right" },
  colRisk: { width: "20%", textAlign: "right" },
  thText: { fontFamily: "Helvetica-Bold", fontSize: 8, color: "#555" },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, textAlign: "center", fontSize: 8, color: "#999" },
  riskHigh: { color: "#dc2626" },
  riskMed: { color: "#d97706" },
  riskLow: { color: "#059669" },
});

function fmt(n: number): string {
  return `$${n.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
}

function riskStyle(level: string) {
  if (level === "critical" || level === "high") return s.riskHigh;
  if (level === "medium") return s.riskMed;
  return s.riskLow;
}

export function ReportDocument({ data }: { data: ReportData }) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={s.brand}>TariffVerify</Text>
          <Text style={s.date}>{data.date}</Text>
        </View>
        <Text style={s.sub}>{data.companyName}</Text>
        <Text style={s.filename}>{data.filename}</Text>

        <View style={s.statsRow}>
          <View style={s.statBox}>
            <Text style={s.statLabel}>Total Spend</Text>
            <Text style={s.statValue}>{fmt(data.totalSpend)}</Text>
          </View>
          <View style={s.statBox}>
            <Text style={s.statLabel}>Tariff Exposure</Text>
            <Text style={s.statValue}>{fmt(data.totalExposure)}</Text>
          </View>
          <View style={s.statBox}>
            <Text style={s.statLabel}>Effective Rate</Text>
            <Text style={s.statValue}>{data.effectiveRate}%</Text>
          </View>
          <View style={s.statBox}>
            <Text style={s.statLabel}>Items at Risk</Text>
            <Text style={s.statValue}>{data.itemsAtRisk}</Text>
          </View>
        </View>

        <View style={s.tableHeader}>
          <Text style={[s.thText, s.colName]}>Item Name</Text>
          <Text style={[s.thText, s.colCountry]}>Country</Text>
          <Text style={[s.thText, s.colSpend]}>Annual Spend</Text>
          <Text style={[s.thText, s.colRate]}>Rate</Text>
          <Text style={[s.thText, s.colCost]}>Tariff Cost</Text>
          <Text style={[s.thText, s.colRisk]}>Risk Level</Text>
        </View>
        {data.items.map((it, i) => (
          <View key={i} style={s.tableRow} wrap={false}>
            <Text style={s.colName}>{it.item_name}</Text>
            <Text style={s.colCountry}>{it.supplier_country}</Text>
            <Text style={s.colSpend}>{fmt(it.annual_spend)}</Text>
            <Text style={s.colRate}>{it.tariff_rate}%</Text>
            <Text style={s.colCost}>{fmt(it.tariff_cost)}</Text>
            <Text style={[s.colRisk, riskStyle(it.risk_level)]}>{it.risk_level}</Text>
          </View>
        ))}

        <Text style={s.footer}>Generated by TariffVerify.com</Text>
      </Page>
    </Document>
  );
}
